### ISSUE TITLE
Virus Total detects malware

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [AvsPmod/AvsPmod#35]
Win32.Trojan.KryptikV.s | 20180130
Backdoor.CPEX.Win32.34512

https://www.virustotal.com/en/file/309d959fb0db79cd0da1092e9e504f04a8c69291350b49602b063fcea53763bd/analysis/1517375222/

**Comment by vdcrim** [comment]
It's a false positive. Executables files are compressed with UPX, some antivirus software don't like it.

**Comment by Vulgaris-Viridis** [comment]
Thanks.
